import java.sql.*;

public class InsertDataToTable {
    public static void main(String[] args) {
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:identifier.sqlite");
             Statement statement = connection.createStatement()) {

            // Создание таблицы, если она не существует
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS words (" +
                    "id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    "word TEXT, " +
                    "category TEXT)");

// Овощи
            insertUniqueWord(statement, "морковь", "Овощи");
            insertUniqueWord(statement, "картофель", "Овощи");
            insertUniqueWord(statement, "помидор", "Овощи");
            insertUniqueWord(statement, "огурец", "Овощи");
            insertUniqueWord(statement, "баклажан", "Овощи");
            insertUniqueWord(statement, "шпинат", "Овощи");
            insertUniqueWord(statement, "капуста", "Овощи");
            insertUniqueWord(statement, "лук", "Овощи");
            insertUniqueWord(statement, "чеснок", "Овощи");
            insertUniqueWord(statement, "перец", "Овощи");
            insertUniqueWord(statement, "брокколи", "Овощи");
            insertUniqueWord(statement, "тушенка", "Овощи");
            insertUniqueWord(statement, "салат", "Овощи");
            insertUniqueWord(statement, "горох", "Овощи");
            insertUniqueWord(statement, "кабачок", "Овощи");
            insertUniqueWord(statement, "редис", "Овощи");
            insertUniqueWord(statement, "спаржа", "Овощи");
            insertUniqueWord(statement, "фасоль", "Овощи");
            insertUniqueWord(statement, "грибы", "Овощи");
            insertUniqueWord(statement, "шалфей", "Овощи");
            insertUniqueWord(statement, "яблоко", "Фрукты");
            insertUniqueWord(statement, "апельсин", "Фрукты");
            insertUniqueWord(statement, "банан", "Фрукты");
            insertUniqueWord(statement, "груша", "Фрукты");
            insertUniqueWord(statement, "ананас", "Фрукты");
            insertUniqueWord(statement, "виноград", "Фрукты");
            insertUniqueWord(statement, "мандарин", "Фрукты");
            insertUniqueWord(statement, "лимон", "Фрукты");
            insertUniqueWord(statement, "киви", "Фрукты");
            insertUniqueWord(statement, "арбуз", "Фрукты");
            insertUniqueWord(statement, "дыня", "Фрукты");
            insertUniqueWord(statement, "гранат", "Фрукты");
            insertUniqueWord(statement, "слива", "Фрукты");
            insertUniqueWord(statement, "абрикос", "Фрукты");
            insertUniqueWord(statement, "вишня", "Фрукты");
            insertUniqueWord(statement, "персик", "Фрукты");
            insertUniqueWord(statement, "грейпфрут", "Фрукты");
            insertUniqueWord(statement, "ежевика", "Фрукты");
            insertUniqueWord(statement, "крыжовник", "Фрукты");
            insertUniqueWord(statement, "шелковица", "Фрукты");
            insertUniqueWord(statement, "укроп", "Зелень");
            insertUniqueWord(statement, "петрушка", "Зелень");
            insertUniqueWord(statement, "шпинат", "Зелень");
            insertUniqueWord(statement, "базилик", "Зелень");
            insertUniqueWord(statement, "мята", "Зелень");
            insertUniqueWord(statement, "кориандр", "Зелень");
            insertUniqueWord(statement, "розмарин", "Зелень");
            insertUniqueWord(statement, "сельдерей", "Зелень");
            insertUniqueWord(statement, "лук-порей", "Зелень");
            insertUniqueWord(statement, "эстрагон", "Зелень");
            insertUniqueWord(statement, "карри", "Зелень");
            insertUniqueWord(statement, "хрен", "Зелень");
            insertUniqueWord(statement, "бадьян", "Зелень");
            insertUniqueWord(statement, "мелисса", "Зелень");
            insertUniqueWord(statement, "мята перечная", "Зелень");
            insertUniqueWord(statement, "листовой салат", "Зелень");
            insertUniqueWord(statement, "лавровый лист", "Зелень");
            insertUniqueWord(statement, "крапива", "Зелень");
            insertUniqueWord(statement, "стевия", "Зелень");
            insertUniqueWord(statement, "тархун", "Зелень");
            insertUniqueWord(statement, "хризантема", "Зелень");
            insertUniqueWord(statement, "рыба", "Морепродукты");
            insertUniqueWord(statement, "молоко", "Молочные продукты");
            insertUniqueWord(statement, "хлеб", "Хлебобулочные изделия");
            insertUniqueWord(statement, "масло", "Масла и жиры");
            insertUniqueWord(statement, "крупа", "Крупы");
            insertUniqueWord(statement, "яйцо", "Яйца");
            insertUniqueWord(statement, "мясо", "Мясо и птица");
            insertUniqueWord(statement, "конфеты", "Сладости");
            insertUniqueWord(statement, "сок", "Напитки");
            insertUniqueWord(statement, "кофе", "Кофе и чай");
            insertUniqueWord(statement, "кетчуп", "Соусы и приправы");
            insertUniqueWord(statement, "горчица", "Соусы и приправы");
            insertUniqueWord(statement, "майонез", "Соусы и приправы");
            insertUniqueWord(statement, "соевый соус", "Соусы и приправы");
            insertUniqueWord(statement, "рыбный соус", "Соусы и приправы");
            insertUniqueWord(statement, "терияки соус", "Соусы и приправы");
            insertUniqueWord(statement, "мед", "Сладости");
            insertUniqueWord(statement, "шоколад", "Сладости");
            insertUniqueWord(statement, "вафли", "Сладости");
            insertUniqueWord(statement, "мармелад", "Сладости");
            insertUniqueWord(statement, "печенье", "Сладости");
            insertUniqueWord(statement, "чипсы", "Снеки");
            insertUniqueWord(statement, "орехи", "Снеки");
            insertUniqueWord(statement, "попкорн", "Снеки");
            insertUniqueWord(statement, "сухарики", "Снеки");
            insertUniqueWord(statement, "пряники", "Сладости");
            insertUniqueWord(statement, "кекс", "Сладости");
            insertUniqueWord(statement, "мороженое", "Десерты");
            insertUniqueWord(statement, "творог", "Молочные продукты");
            insertUniqueWord(statement, "кефир", "Молочные продукты");
            insertUniqueWord(statement, "сметана", "Молочные продукты");
            insertUniqueWord(statement, "йогурт", "Молочные продукты");
            insertUniqueWord(statement, "сыр", "Молочные продукты");
            insertUniqueWord(statement, "сгущенное молоко", "Молочные продукты");
            insertUniqueWord(statement, "творожок", "Молочные продукты");
            insertUniqueWord(statement, "молочный коктейль", "Напитки");
            insertUniqueWord(statement, "газировка", "Напитки");
            insertUniqueWord(statement, "вода", "Напитки");
            insertUniqueWord(statement, "сок из апельсина", "Напитки");
            insertUniqueWord(statement, "сок из яблока", "Напитки");
            insertUniqueWord(statement, "чай зеленый", "Кофе и чай");
            insertUniqueWord(statement, "чай черный", "Кофе и чай");
            insertUniqueWord(statement, "кофе растворимый", "Кофе и чай");
            insertUniqueWord(statement, "кофе в зернах", "Кофе и чай");
            insertUniqueWord(statement, "чай травяной", "Кофе и чай");
            insertUniqueWord(statement, "рис", "Крупы");
            insertUniqueWord(statement, "гречка", "Крупы");
            insertUniqueWord(statement, "пшено", "Крупы");
            insertUniqueWord(statement, "манная крупа", "Крупы");
            insertUniqueWord(statement, "кускус", "Крупы");
            insertUniqueWord(statement, "пшеница", "Крупы");
            insertUniqueWord(statement, "макароны", "Крупы");
            insertUniqueWord(statement, "грибы", "Консервы");
            insertUniqueWord(statement, "консервированные овощи", "Консервы");
            insertUniqueWord(statement, "тушенка", "Консервы");
            insertUniqueWord(statement, "рыбные консервы", "Консервы");
            insertUniqueWord(statement, "супы готовые", "Консервы");
            insertUniqueWord(statement, "говядина", "Мясо");
            insertUniqueWord(statement, "курица", "Мясо");
            insertUniqueWord(statement, "свинина", "Мясо");
            insertUniqueWord(statement, "баранина", "Мясо");
            insertUniqueWord(statement, "колбаса", "Мясные изделия");
            insertUniqueWord(statement, "сосиски", "Мясные изделия");
            insertUniqueWord(statement, "ветчина", "Мясные изделия");
            insertUniqueWord(statement, "салями", "Мясные изделия");
            insertUniqueWord(statement, "бекон", "Мясные изделия");
            insertUniqueWord(statement, "оливки", "Маринады и соленья");
            insertUniqueWord(statement, "каперсы", "Маринады и соленья");
            insertUniqueWord(statement, "маринованные огурцы", "Маринады и соленья");
            insertUniqueWord(statement, "маринованные грибы", "Маринады и соленья");
            insertUniqueWord(statement, "маринованные помидоры", "Маринады и соленья");
            insertUniqueWord(statement, "сливки", "Молочные продукты");
            insertUniqueWord(statement, "кефирный гриб", "Молочные продукты");
            insertUniqueWord(statement, "растительное масло", "Масла");
            insertUniqueWord(statement, "сливочное масло", "Масла");
            insertUniqueWord(statement, "подсолнечное масло", "Масла");
            insertUniqueWord(statement, "оливковое масло", "Масла");
            insertUniqueWord(statement, "кунжутное масло", "Масла");
            insertUniqueWord(statement, "грейпфрут", "Фрукты");
            insertUniqueWord(statement, "лимон", "Фрукты");
            insertUniqueWord(statement, "манго", "Фрукты");
            insertUniqueWord(statement, "ананас", "Фрукты");
            insertUniqueWord(statement, "виноград", "Фрукты");
            insertUniqueWord(statement, "кабачок", "Овощи");
            insertUniqueWord(statement, "брокколи", "Овощи");
            insertUniqueWord(statement, "шпинат", "Овощи");
            insertUniqueWord(statement, "баклажан", "Овощи");
            insertUniqueWord(statement, "лук", "Овощи");
            insertUniqueWord(statement, "шалфей", "Зелень");
            insertUniqueWord(statement, "укроп", "Зелень");
            insertUniqueWord(statement, "петрушка", "Зелень");
            insertUniqueWord(statement, "базилик", "Зелень");
            insertUniqueWord(statement, "сельдерей", "Зелень");
            insertUniqueWord(statement, "яйца", "Яйца и молочные продукты");
            insertUniqueWord(statement, "сметана", "Яйца и молочные продукты");
            insertUniqueWord(statement, "творог", "Яйца и молочные продукты");
            insertUniqueWord(statement, "сливочное масло", "Яйца и молочные продукты");
            insertUniqueWord(statement, "сыр", "Яйца и молочные продукты");
            insertUniqueWord(statement, "майонез", "Соусы и приправы");
            insertUniqueWord(statement, "горчица", "Соусы и приправы");
            insertUniqueWord(statement, "кетчуп", "Соусы и приправы");
            insertUniqueWord(statement, "соевый соус", "Соусы и приправы");
            insertUniqueWord(statement, "сырники", "Выпечка");
            insertUniqueWord(statement, "пирог", "Выпечка");
            insertUniqueWord(statement, "булочка", "Выпечка");
            insertUniqueWord(statement, "багет", "Выпечка");
            insertUniqueWord(statement, "плюшка", "Выпечка");
            insertUniqueWord(statement, "фасоль", "Бобовые");
            insertUniqueWord(statement, "горох", "Бобовые");
            insertUniqueWord(statement, "чечевица", "Бобовые");
            insertUniqueWord(statement, "какао порошок", "Кофе и чай");
            insertUniqueWord(statement, "кофейные зерна", "Кофе и чай");
            insertUniqueWord(statement, "сахар", "Сладости");
            insertUniqueWord(statement, "сгущенка", "Сладости");
            insertUniqueWord(statement, "пудинг", "Десерты");
            insertUniqueWord(statement, "желе", "Десерты");
            insertUniqueWord(statement, "крем", "Десерты");
            insertUniqueWord(statement, "творожная запеканка", "Десерты");
            insertUniqueWord(statement, "роллы", "Суши и роллы");
            insertUniqueWord(statement, "суши", "Суши и роллы");
            insertUniqueWord(statement, "нори", "Суши и роллы");
            insertUniqueWord(statement, "соевый соус", "Суши и роллы");
            insertUniqueWord(statement, "капуста", "Овощи");
            insertUniqueWord(statement, "брюква", "Овощи");
            insertUniqueWord(statement, "топинамбур", "Овощи");
            insertUniqueWord(statement, "топинамбур", "Овощи");
            insertUniqueWord(statement, "шпинат", "Овощи");
            insertUniqueWord(statement, "ревень", "Овощи");
            insertUniqueWord(statement, "малина", "Ягоды");
            insertUniqueWord(statement, "ежевика", "Ягоды");
            insertUniqueWord(statement, "клубника", "Ягоды");
            insertUniqueWord(statement, "черника", "Ягоды");
            insertUniqueWord(statement, "голубика", "Ягоды");
            insertUniqueWord(statement, "мак", "Мука и тесто");
            insertUniqueWord(statement, "мука", "Мука и тесто");
            insertUniqueWord(statement, "дрожжи", "Мука и тесто");
            insertUniqueWord(statement, "сахарная пудра", "Сладости");
            insertUniqueWord(statement, "печенье", "Сладости");
            insertUniqueWord(statement, "варенье", "Сладости");
            insertUniqueWord(statement, "пряники", "Сладости");
            insertUniqueWord(statement, "рисовая лапша", "Макаронные изделия");
            insertUniqueWord(statement, "спагетти", "Макаронные изделия");
            insertUniqueWord(statement, "вермишель", "Макаронные изделия");
            insertUniqueWord(statement, "лапша яичная", "Макаронные изделия");
            insertUniqueWord(statement, "хлеб", "Хлебобулочные изделия");
            insertUniqueWord(statement, "багет", "Хлебобулочные изделия");
            insertUniqueWord(statement, "ржаной хлеб", "Хлебобулочные изделия");
            insertUniqueWord(statement, "хлебцы", "Хлебобулочные изделия");
            insertUniqueWord(statement, "сосиски", "Колбасные изделия");
            insertUniqueWord(statement, "колбаса", "Колбасные изделия");
            insertUniqueWord(statement, "пастрами", "Колбасные изделия");
            insertUniqueWord(statement, "колбаски", "Колбасные изделия");
            insertUniqueWord(statement, "пельмени", "Замороженные продукты");
            insertUniqueWord(statement, "вареники", "Замороженные продукты");
            insertUniqueWord(statement, "креветки", "Морепродукты");
            insertUniqueWord(statement, "лосось", "Морепродукты");
            insertUniqueWord(statement, "тунец", "Морепродукты");
            insertUniqueWord(statement, "крабовые палочки", "Морепродукты");
            insertUniqueWord(statement, "хек", "Морепродукты");
            insertUniqueWord(statement, "персик", "Фрукты");
            insertUniqueWord(statement, "груша", "Фрукты");
            insertUniqueWord(statement, "слива", "Фрукты");

            System.out.println("Данные успешно добавлены в таблицу.");
        } catch (SQLException e) {
            System.out.println("Ошибка при работе с базой данных: " + e.getMessage());
        }
    }

    private static void insertUniqueWord(Statement statement, String word, String category) throws SQLException {
        String sql = "INSERT INTO words (word, category) " +
                "SELECT ? AS word, ? AS category " +
                "WHERE NOT EXISTS (SELECT 1 FROM words WHERE word = ? AND category = ?)";
        try (PreparedStatement preparedStatement = statement.getConnection().prepareStatement(sql)) {
            preparedStatement.setString(1, word);
            preparedStatement.setString(2, category);
            preparedStatement.setString(3, word);
            preparedStatement.setString(4, category);
            preparedStatement.executeUpdate();
        }
    }
}
